name: Deploy 11ty to NekoWeb

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  

    - name: Install dependencies
      run: npm install

    - name: Build 11ty site
      run: npx @11ty/eleventy --debug

    - name: Prepare build
      run: |
          mkdir -p ./build
          cp -r ./public/* ./build

    - name: Deploy to Nekoweb
      uses: mp-pinheiro/nekoweb-deploy@main
      with:
        API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
        BUILD_DIR: './build'
        DEPLOY_DIR: '/'
        CLEANUP: 'False'
        DELAY: '0.5'
        NEKOWEB_PAGENAME: 'ironstar'
